org.gradle.jvmargs=-Xmx6144m -XX:+UseParallelGC -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=4
org.gradle.vfs.watch=false
android.useAndroidX=true
android.nonFinalResIds=false
kotlin.code.style=official
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2048m -XX:+UseParallelGC
ksp.incremental=true
